[2021-12-21 11:42:01,916]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=SKC&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 11:45:41,957]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=SKC&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 11:45:58,896]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=SKC&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 11:47:24,884]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=%E5%B9%BF%E4%B8%9C%E7%9C%81%E7%9F%B3%E9%BE%99%E9%95%87%E4%BA%AC%E7%93%B7%E8%B7%AF%E5%85%AB%E5%8F%B7&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 14:21:18,193]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=%E7%A4%BE%E8%B4%9D%E6%9D%91&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 14:21:19,163]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=%E5%B9%BF%E5%B7%9E%E5%B8%82%E8%8A%B1%E9%83%BD%E5%8C%BA%E6%9C%BA%E5%9C%BA%E5%A4%A7%E9%81%93%E4%B8%9C888%E5%8F%B7&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[2021-12-21 14:21:19,165]-[baiduapi.py]-[get_driving_direction]-[117]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: 'NoneType' object is not subscriptable
[2021-12-21 14:21:40,790]-[baiduapi.py]-[getplace_byabbreviation]-[97]-12s: [ERROR]-8s>> 调用百度api获取地点信息出错！：Unexpected Error: HTTPSConnectionPool(host='api.map.baidu.com', port=443): Max retries exceeded with url: /geocoding/v3/?address=%E7%A4%BE%E8%B4%9D%E6%9D%91&output=json&ak=5FOb4Fa180itR3lIYyhC2MU7FQEsdBbq (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
