[2021-12-16 11:50:35,039]-[object.py]-[<module>]-[296]-12s: [INFO]-8s>> ces
[2021-12-16 11:50:35,041]-[object.py]-[<module>]-[297]-12s: [INFO]-8s>> hello
[2021-12-16 11:52:11,107]-[object.py]-[get_apply_data]-[218]-12s: [ERROR]-8s>> request获取明细信息出错，错误单号：GA03-202112-47232：Unexpected Error: HTTPConnectionPool(host='10.9.140.98', port=80): Max retries exceeded with url: /workflow_skc/apps/index.cfm?fuseaction=inquiryall.ApplyDisp&ApplyID=297098 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002721EF7A108>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2021-12-16 11:53:42,899]-[object.py]-[<module>]-[296]-12s: [INFO]-8s>> ces
[2021-12-16 11:53:42,900]-[object.py]-[<module>]-[297]-12s: [INFO]-8s>> hello
[2021-12-16 14:55:32,973]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:55:32,973]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:55:32,978]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:55:32,978]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:57:21,568]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:57:21,568]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:57:21,569]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:57:21,569]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:57:52,876]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:57:52,876]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:57:52,877]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:57:52,877]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:59:48,346]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:59:48,346]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 14:59:48,347]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 14:59:48,347]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:03:11,007]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:03:11,007]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:03:11,008]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:03:11,008]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:06:27,628]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:06:27,628]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:06:27,629]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:06:27,629]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:07:14,804]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: list indices must be integers or slices, not str
[2021-12-16 15:07:14,804]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: list indices must be integers or slices, not str
[2021-12-16 15:12:01,300]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:12:01,300]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:12:01,301]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:12:01,301]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:13:57,286]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:13:57,286]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:13:57,287]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:13:57,287]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:14:19,564]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'applytpye'
[2021-12-16 15:14:19,564]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'applytpye'
[2021-12-16 15:17:27,895]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:17:27,895]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:17:27,896]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:17:27,896]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:18:10,411]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: list indices must be integers or slices, not str
[2021-12-16 15:18:10,411]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: list indices must be integers or slices, not str
[2021-12-16 15:19:31,407]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:19:31,407]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:19:31,408]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:19:31,408]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:20:03,670]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'DetailedAddres'
[2021-12-16 15:20:03,670]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'DetailedAddres'
[2021-12-16 15:20:59,008]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:20:59,008]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:20:59,009]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:20:59,009]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:22:08,194]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:22:08,194]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:22:08,195]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:22:08,195]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:22:27,846]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'PhonePassenger'
[2021-12-16 15:22:27,846]-[pyslserver.py]-[dictToTO]-[203]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'PhonePassenger'
[2021-12-16 15:23:25,604]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:23:25,604]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:23:25,605]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:23:25,605]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:36:22,403]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:36:22,403]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:36:22,404]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:36:22,404]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:41:29,643]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:41:29,643]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:41:29,644]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:41:29,644]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:41:37,094]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:41:37,094]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:41:40,917]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-2转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:41:40,917]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-2转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:41:46,110]-[CasSystemScrapy.py]-[get_apply_data]-[315]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-16 15:41:46,110]-[CasSystemScrapy.py]-[get_apply_data]-[315]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-16 15:42:35,413]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:42:35,413]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:42:35,413]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:42:35,413]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:42:59,826]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:42:59,826]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'dict' object has no attribute 'append'
[2021-12-16 15:43:35,714]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:43:35,714]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> ces
[2021-12-16 15:43:35,715]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 15:43:35,715]-[CasSystemScrapy.py]-[<module>]-[321]-12s: [INFO]-8s>> hello
[2021-12-16 16:03:28,599]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:03:28,599]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:03:28,600]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:03:28,600]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:23:55,665]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:23:55,665]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:23:55,666]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:23:55,666]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:27:47,020]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:27:47,020]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:27:47,021]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:27:47,021]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:28:10,230]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'UUID' object has no attribute 'split'
[2021-12-16 16:28:10,230]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: 'UUID' object has no attribute 'split'
[2021-12-16 16:28:21,208]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-2转化为sql出错：Unexpected Error: 'UUID' object has no attribute 'split'
[2021-12-16 16:28:21,208]-[pyslserver.py]-[dictToTO]-[205]-12s: [ERROR]-8s>> 将派车单号GA-202112-2转化为sql出错：Unexpected Error: 'UUID' object has no attribute 'split'
[2021-12-16 16:28:27,660]-[CasSystemScrapy.py]-[get_apply_data]-[314]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-16 16:28:27,660]-[CasSystemScrapy.py]-[get_apply_data]-[314]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
[2021-12-16 16:42:52,780]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:42:52,780]-[CasSystemScrapy.py]-[<module>]-[319]-12s: [INFO]-8s>> ces
[2021-12-16 16:42:52,781]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:42:52,781]-[CasSystemScrapy.py]-[<module>]-[320]-12s: [INFO]-8s>> hello
[2021-12-16 16:44:54,082]-[pyslserver.py]-[dictToTO]-[207]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: can only concatenate str (not "int") to str
[2021-12-16 16:44:54,082]-[pyslserver.py]-[dictToTO]-[207]-12s: [ERROR]-8s>> 将派车单号GA-202112-3转化为sql出错：Unexpected Error: can only concatenate str (not "int") to str
[2021-12-16 16:45:11,182]-[object.py]-[<module>]-[299]-12s: [INFO]-8s>> ces
[2021-12-16 16:45:11,183]-[object.py]-[<module>]-[300]-12s: [INFO]-8s>> hello
